export const PARALLELS = [
  { variant: "Base", hover: "", subtitle: "", collected: true },
  {
    variant: "Refractor",
    hover: "1:3 hobby / 1:1 jumbo / 1:! breaker / 1:4 value / 1:3 monster",
    subtitle: "",
    collected: true,
  },
  {
    variant: "Pink Refractor",
    hover: "1:4 value",
    subtitle: "",
    collected: true,
  },
  {
    variant: "Prism Refactor",
    hover: "1:6 hobby / 1:2 jumbo / 1:7 value / 1:7 monster",
    subtitle: "",
    collected: true,
  },
  {
    variant: "RayWave Refractor",
    hover: "1:9 value / 1:4 monster",
    subtitle: "",
    collected: true,
  },
  { variant: "Sepia", hover: "1:4 value", subtitle: "", collected: true },
  {
    variant: "X Refractor",
    hover: "1:1 monster",
    subtitle: "",
    collected: false,
  },
  {
    variant: "Negative Refractor",
    hover: "1:89 hobby, 1:27 jumbo, 1:3 breaker, 1:249 value, 1:101 monster",
    subtitle: "",
    collected: true,
  },
  {
    variant: "Magenta Speckle Refractor",
    hover: "1:102 hobby, 1:31 jumbo, 1:3 breaker, 1:285 value, 1:116 monster",
    subtitle: "185/350",
    collected: true,
  },
  {
    variant: "Purple Speckle Refractor",
    hover: "1:119 hobby, 1:36 jumbo, 1:3 breaker, 1:334 value, 1:136 monster",
    subtitle: "81/299",
    collected: true,
  },
  {
    variant: "Sonar Purple Refractor",
    hover: "1:109 value, 1:73 monster",
    subtitle: "/275",
    collected: false,
  },
  {
    variant: "Purple Refractor",
    hover: "1:143 hobby, 1:44 jumbo, 1:4 breaker, 1:403 value, 1:164 monster",
    subtitle: "/250",
    collected: false,
  },
  {
    variant: "Aqua Refractor",
    hover: "1:179 hobby, 1:55 jumbo, 1:5 breaker, 1:503 value, 1:205 monster",
    subtitle: "/199",
    collected: false,
  },
  {
    variant: "Aqua Lava Refractor",
    hover: "1:179 hobby, 1:55 jumbo, 1:5 breaker, 1:503 value, 1:205 monster",
    subtitle: "141/199",
    collected: true,
  },
  {
    variant: "RayWave Aqua Refractor",
    hover: "1:151 value, 1:101 monster",
    subtitle: "/199",
    collected: false,
  },
  {
    variant: "Blue Refractor",
    hover: "1:238 hobby, 1:73 jumbo, 1:6 breaker, 1:669 value, 1:271 monster",
    subtitle: "/150",
    collected: false,
  },
  {
    variant: "RayWave Blue Refractor",
    hover: "1:200 value, 1:134 monster",
    subtitle: "/150",
    collected: false,
  },
  {
    variant: "Sonar Blue Refractor",
    hover: "1:285 hobby, 1:87 jumbo, 1:7 breaker, 1:804 value, 1:326 monster",
    subtitle: "/125",
    collected: false,
  },
  {
    variant: "Lightboard Logo",
    hover: "1:280 value, 1:140 monster",
    subtitle: "",
    collected: false,
  },
  {
    variant: "Green Refractor",
    hover:
      "1:361 hobby, 1:110 jumbo, 1:9 breaker, 1:1,016 value, 1:413 monster",
    subtitle: "/99",
    collected: false,
  },
  {
    variant: "Green Wave Refractor",
    hover: "1:185 hobby, 1:57 jumbo, 1:62 breaker",
    subtitle: "/99",
    collected: false,
  },
  {
    variant: "RayWave Green Refractor",
    hover: "1:304 value, 1:203 monster",
    subtitle: "/99",
    collected: false,
  },
  {
    variant: "Sonar Green Refractors",
    hover:
      "1:361 hobby, 1:110 jumbo, 1:9 breaker, 1:1,016 value, 1:413 monster",
    subtitle: "1/99",
    collected: true,
  },
  {
    variant: "Blue Wave Refractors",
    hover: "1:245 hobby, 1:76 jumbo, 1:82 breaker",
    subtitle: "/75",
    collected: false,
  },
  {
    variant: "Gold Refractors",
    hover:
      "1:714 hobby, 1:218 jumbo, 1:18 breaker, 1:2,014 value, 1:817 monster",
    subtitle: "/50",
    collected: false,
  },
  {
    variant: "Gold Wave Refractors",
    hover: "1:367 hobby, 1:113 jumbo, 1:122 breaker",
    subtitle: "/50",
    collected: false,
  },
  {
    variant: "RayWave Gold Refractors",
    hover: "1:601 value, 1:402 monster",
    subtitle: "/50",
    collected: false,
  },
  {
    variant: "Big Apple Refractors",
    hover: "Fanatics Fest NYC boxes only",
    subtitle: "/50",
    collected: false,
  },
  {
    variant: "Orange Refractors",
    hover: "1:388 hobby",
    subtitle: "/25",
    collected: false,
  },
  {
    variant: "Orange Wave Refractors",
    hover: "1:733 hobby, 1:226 jumbo, 1:244 breaker",
    subtitle: "/25",
    collected: false,
  },
  {
    variant: "RayWave Orange Refractors",
    hover: "1:1,201 value, 1:800 monster",
    subtitle: "/25",
    collected: false,
  },
  {
    variant: "Black Refractors",
    hover: "1:1,833 hobby, 1:564 jumbo, 1:626 breaker",
    subtitle: "/10",
    collected: false,
  },
  {
    variant: "RayWave Black Refractors",
    hover: "1:3,012 value, 1:2,013 monster",
    subtitle: "/10",
    collected: false,
  },
  {
    variant: "Frozenfractors",
    hover: "1:506 jumbo",
    subtitle: "/5",
    collected: false,
  },
  {
    variant: "Red Refractors",
    hover:
      "1:7,117 hobby, 1:2,163 jumbo, 1:173 breaker, 1:20,184 value, 1:8,336 monster",
    subtitle: "/5",
    collected: false,
  },
  {
    variant: "Red Wave Refractors",
    hover: "1:3,657 hobby, 1:1,127 jumbo, 1:1,251 breaker",
    subtitle: "/5",
    collected: false,
  },
  {
    variant: "RayWave Red Refractors",
    hover: "1:6,024 value, 1:4,025 monster",
    subtitle: "/5",
    collected: false,
  },
  {
    variant: "Printing Plates",
    hover:
      "1:8,896 hobby, 1:2,722 jumbo, 1:218 breaker, 1:25,281 value, 1:10,610 monster; each has Black, Cyan, Magenta and Yellow versions",
    subtitle: "1/1",
    collected: false,
  },
  {
    variant: "Superfractors",
    hover:
      "1:35,584 hobby, 1:11,011 jumbo, 1:834 breaker, 1:104,587 value, 1:40,062 monster",
    subtitle: "1/1",
    collected: false,
  },
];